// packages/react/src/BaseUrlInput.tsx
import { useState } from 'react';
import type { Provider, Language } from '@tombcato/ai-selector-core';
import { I18N } from '@tombcato/ai-selector-core';

interface BaseUrlInputProps {
    provider: Provider | null;
    baseUrl: string;
    onChange: (value: string) => void;
    disabled?: boolean;
    language?: Language;
}

export function BaseUrlInput({
    provider,
    baseUrl,
    onChange,
    disabled,
    language = 'zh'
}: BaseUrlInputProps) {
    const [isOpen, setIsOpen] = useState(false);
    const t = I18N[language];

    if (!provider) return null;

    return (
        <>
            <button
                type="button"
                onClick={() => setIsOpen(!isOpen)}
                className="text-xs text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 flex items-center gap-1 transition-colors"
            >
                <svg
                    className={`w-3 h-3 transition-transform ${isOpen ? 'rotate-90' : ''}`}
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                >
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                </svg>
                {t.customBaseUrl}
            </button>

            <div
                className="grid transition-all duration-200 ease-out"
                style={{ gridTemplateRows: isOpen ? '1fr' : '0fr' }}
            >
                <div className="overflow-hidden">
                    <input
                        type="text"
                        value={baseUrl}
                        onChange={(e) => onChange(e.target.value)}
                        placeholder={provider.baseUrl}
                        disabled={disabled}
                        className="apmsu-input apmsu-input-default"
                    />
                </div>
            </div>
        </>
    );
}

// packages/vue/src/BaseUrlInput.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import { I18N, type Language, type Provider } from '@tombcato/ai-selector-core';

interface Props {
  provider: Provider | null;
  baseUrl: string;
  disabled?: boolean;
  language?: Language;
}

const props = withDefaults(defineProps<Props>(), {
  disabled: false,
  language: 'zh',
});

const emit = defineEmits<{
  'update:baseUrl': [value: string];
}>();

const isOpen = ref(false);
const t = computed(() => I18N[props.language]);
</script>

<template>
  <template v-if="provider">
    <button
      type="button"
      @click="isOpen = !isOpen"
      class="text-xs text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 flex items-center gap-1 transition-colors"
    >
      <svg 
        :class="['w-3 h-3 transition-transform', isOpen && 'rotate-90']" 
        fill="none" 
        stroke="currentColor" 
        viewBox="0 0 24 24"
      >
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
      </svg>
      {{ t.customBaseUrl }}
    </button>

    <div
      class="grid transition-all duration-200 ease-out"
      :style="{ gridTemplateRows: isOpen ? '1fr' : '0fr' }"
    >
      <div class="overflow-hidden">
        <input
          type="text"
          :value="baseUrl"
          @input="emit('update:baseUrl', ($event.target as HTMLInputElement).value)"
          :placeholder="provider.baseUrl"
          :disabled="disabled"
          class="apmsu-input apmsu-input-default"
        />
      </div>
    </div>
  </template>
</template>
