// packages/react/src/ModelSelect.tsx
import { useRef, useEffect, useState } from 'react';
import type { Model, Provider, Language } from '@tombcato/ai-selector-core';
import { I18N } from '@tombcato/ai-selector-core';
import { SmartText } from './SmartText';

interface ModelSelectProps {
    provider: Provider | null;
    models: Model[];
    selectedModelId: string;
    onSelect: (modelId: string, modelName?: string) => void;
    isOpen: boolean;
    setIsOpen: (isOpen: boolean) => void;
    hasApiKey: boolean;
    disabled?: boolean;
    language?: Language;
    isFetchingModels?: boolean;
    fetchModelError?: string | null;
    selectedModelName?: string;
}

export function ModelSelect({
    provider,
    models,
    selectedModelId,
    onSelect,
    isOpen,
    setIsOpen,
    hasApiKey,
    disabled,
    language = 'zh',
    isFetchingModels,
    fetchModelError,
    selectedModelName
}: ModelSelectProps) {
    const t = I18N[language];
    const triggerRef = useRef<HTMLDivElement>(null);
    const [modelSearch, setModelSearch] = useState('');
    const searchInputRef = useRef<HTMLInputElement>(null);

    useEffect(() => {
        if (isOpen && searchInputRef.current) {
            setTimeout(() => {
                searchInputRef.current?.focus();
            }, 200);
        }
    }, [isOpen]);

    useEffect(() => {
        const handleClickOutside = (e: MouseEvent) => {
            if (triggerRef.current && !triggerRef.current.contains(e.target as Node)) {
                setIsOpen(false);
                setModelSearch('');
            }
        };
        document.addEventListener('mousedown', handleClickOutside);
        return () => document.removeEventListener('mousedown', handleClickOutside);
    }, [setIsOpen]);

    const filteredModels = models.filter(m =>
        m.name.toLowerCase().includes(modelSearch.toLowerCase()) ||
        m.id.toLowerCase().includes(modelSearch.toLowerCase())
    );

    const activeModelName = models.find(m => m.id === selectedModelId)?.name || selectedModelName || selectedModelId;

    return (
        <div className="apmsu-field" ref={triggerRef}>
            <label className="apmsu-label flex items-center justify-between">
                <span>{t.modelLabel}</span>
            </label>
            <div className="relative">
                <button
                    type="button"
                    onClick={() => !disabled && provider && setIsOpen(!isOpen)}
                    disabled={disabled || !provider}
                    className="apmsu-select-trigger"
                >
                    <SmartText
                        text={activeModelName}
                        placeholder={t.selectModel}
                    />
                    <ChevronIcon isOpen={isOpen} />
                </button>

                <div className={`apmsu-dropdown origin-top ${isOpen ? 'apmsu-dropdown-open' : ''}`}>
                    <div className="p-1.5 apmsu-divider">
                        <input
                            ref={searchInputRef}
                            type="text"
                            value={modelSearch}
                            onChange={(e) => setModelSearch(e.target.value)}
                            placeholder={t.searchModel}
                            className="apmsu-select-trigger"
                        />
                    </div>
                    <div className="max-h-60 overflow-auto">
                        {/* Custom model option */}
                        {modelSearch && !filteredModels.some(m => m.id === modelSearch) && (
                            <button
                                type="button"
                                onClick={() => {
                                    onSelect(modelSearch);
                                    setIsOpen(false);
                                    setModelSearch('');
                                }}
                                className="apmsu-dropdown-item bg-blue-50 dark:bg-blue-900/20 border-b"
                            >
                                <span className="text-blue-500">{t.useCustom}: {modelSearch}</span>
                            </button>
                        )}
                        {filteredModels.map((m: Model) => (
                            <button
                                key={m.id}
                                type="button"
                                onClick={() => {
                                    onSelect(m.id, m.name);
                                    setIsOpen(false);
                                    setModelSearch('');
                                }}
                                className={`apmsu-dropdown-item ${selectedModelId === m.id ? 'apmsu-dropdown-item-active' : ''}`}
                            >
                                <span>{m.name}</span>
                            </button>
                        ))}
                        {filteredModels.length === 0 && !modelSearch && (
                            <div className="p-4 text-center apmsu-hint-text">{t.noModels}</div>
                        )}
                    </div>
                </div>
            </div>

            {/* Status Messages Container - only for supportsModelsApi providers */}
            {provider?.supportsModelsApi && (
                <div className="min-h-[20px] flex items-center">
                    {isFetchingModels ? (
                        <p className="apmsu-hint-text animate-pulse">
                            {t.refreshingModels}
                        </p>
                    ) : fetchModelError ? (
                        <p className="apmsu-hint-text dark:text-zinc-500">
                            {t[fetchModelError as keyof typeof t] || fetchModelError}
                        </p>
                    ) : (provider?.needsApiKey && !hasApiKey) ? (
                        <p className="apmsu-hint-text">{t.apiKeyTip}</p>
                    ) : (
                        <p className="apmsu-hint-text">{t.modelListUpdated}</p>
                    )}
                </div>
            )}
        </div>
    );
}

const ChevronIcon = ({ isOpen }: { isOpen: boolean }) => (
    <svg
        className={`apmsu-chevron ${isOpen ? 'rotate-180' : ''}`}
        fill="none"
        stroke="currentColor"
        viewBox="0 0 24 24"
    >
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
    </svg>
);

// packages/vue/src/ModelSelect.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue';
import { I18N, type Language, type Provider, type Model } from '@tombcato/ai-selector-core';
import SmartText from './SmartText.vue';

interface Props {
  provider: Provider | null;
  models: Model[];
  selectedModelId: string;
  hasApiKey: boolean;
  disabled?: boolean;
  language?: Language;
  isFetchingModels?: boolean;
  fetchModelError?: string | null;
  selectedModelName?: string;
}

const props = withDefaults(defineProps<Props>(), {
  disabled: false,
  language: 'zh',
});

const emit = defineEmits<{
  select: [modelId: string, modelName?: string];
}>();

const isOpen = ref(false);
const modelSearch = ref('');
const triggerRef = ref<HTMLDivElement | null>(null);
const t = computed(() => I18N[props.language]);

const filteredModels = computed(() =>
  props.models.filter(m =>
    m.name.toLowerCase().includes(modelSearch.value.toLowerCase()) ||
    m.id.toLowerCase().includes(modelSearch.value.toLowerCase())
  )
);

const activeModelName = computed(() => 
  props.models.find(m => m.id === props.selectedModelId)?.name || props.selectedModelName || props.selectedModelId
);

function handleClickOutside(e: MouseEvent) {
  if (triggerRef.value && !triggerRef.value.contains(e.target as Node)) {
    isOpen.value = false;
    modelSearch.value = '';
  }
}

onMounted(() => {
  document.addEventListener('mousedown', handleClickOutside);
});

onUnmounted(() => {
  document.removeEventListener('mousedown', handleClickOutside);
});

function handleSelect(id: string, name?: string) {
  emit('select', id, name);
  isOpen.value = false;
  modelSearch.value = '';
}
</script>

<template>
  <div class="apmsu-field" ref="triggerRef">
    <label class="apmsu-label flex items-center justify-between">
      <span>{{ t.modelLabel }}</span>
    </label>
    <div class="relative">
      <button
        type="button"
        @click="!disabled && provider && (isOpen = !isOpen)"
        :disabled="disabled || !provider"
        class="apmsu-select-trigger"
      >
        <SmartText 
          :text="activeModelName ? activeModelName : ''"
          :placeholder="t.selectModel"
        />
        <svg 
          :class="['apmsu-chevron', isOpen ? 'rotate-180' : '']" 
          fill="none" stroke="currentColor" viewBox="0 0 24 24"
        >
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
        </svg>
      </button>

      <div :class="['apmsu-dropdown origin-top', isOpen ? 'apmsu-dropdown-open' : '']">
        <div class="p-1.5 border-b border-gray-100 dark:border-zinc-800">
          <input
            type="text"
            v-model="modelSearch"
            :placeholder="t.searchModel"
            class="apmsu-select-trigger"
            :autofocus="isOpen"
          />
        </div>
        <div class="max-h-60 overflow-auto">
          <button
            v-if="modelSearch && !filteredModels.some(m => m.id === modelSearch)"
            type="button"
            @click="handleSelect(modelSearch)"
            class="apmsu-dropdown-item bg-blue-50 dark:bg-blue-900/20 border-b"
          >
            <span class="text-blue-500">{{ t.useCustom }}: {{ modelSearch }}</span>
          </button>
          <button
            v-for="m in filteredModels"
            :key="m.id"
            type="button"
            @click="handleSelect(m.id, m.name)"
            :class="['apmsu-dropdown-item', selectedModelId === m.id && 'apmsu-dropdown-item-active']"
          >
            <span>{{ m.name }}</span>
          </button>
          <div v-if="filteredModels.length === 0 && !modelSearch" class="p-4 text-center apmsu-hint-text">
            {{ t.noModels }}
          </div>
        </div>
      </div>
    </div>
    
    <!-- Status Messages Container - only for supportsModelsApi providers -->
    <div v-if="provider?.supportsModelsApi" class="min-h-[20px] flex items-center">
      <p v-if="isFetchingModels" class="apmsu-hint-text animate-pulse">
        {{ t.refreshingModels }}
      </p>
      
      <p v-else-if="fetchModelError" class="apmsu-hint-text dark:text-zinc-500">
        {{ (t as any)[fetchModelError] || fetchModelError }}
      </p>

      <p v-else-if="provider?.needsApiKey && !hasApiKey" class="apmsu-hint-text">
        {{ t.apiKeyTip }}
      </p>

      <p v-else class="apmsu-hint-text">
        {{ t.modelListUpdated }}
      </p>
    </div>
  </div>
</template>
