// packages/react/src/SmartText.tsx

import { Ticker as SmartTicker } from '@tombcato/smart-ticker';
import '@tombcato/smart-ticker/style.css';

interface SmartTextProps {
    text: string;
    className?: string;
    placeholder?: string;
}

export function SmartText({ text, className = '', placeholder }: SmartTextProps) {
    if (!text && placeholder) {
        return <span className={`apmsu-placeholder ${className}`}>{placeholder}</span>;
    }

    if (!text) return null;

    return (
        <span className={`inline-flex min-w-0 ${className}`}>
            <SmartTicker value={text} charWidth={0.8} duration={300} />
        </span>
    );
}

// packages/vue/src/SmartText.vue
<script setup lang="ts">
import { Ticker as SmartTicker } from '@tombcato/smart-ticker/vue';
import '@tombcato/smart-ticker/style.css';

const props = defineProps<{
  text?: string;
  className?: string;
  placeholder?: string;
}>();
</script>

<template>
  <span v-if="!text && placeholder" :class="['apmsu-placeholder', className]">
    {{ placeholder }}
  </span>
  <span v-else-if="text" :class="['inline-flex min-w-0', className]">
    <SmartTicker :value="text" :char-width="0.8" :duration="300" />
  </span>
</template>
